version: "3.8"

services:
  demo-app:
    image: kennethreitz/httpbin
    container_name: demo-app
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--enable-feature=remote-write-receiver"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards  
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Admin123!
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_CHANGE=true

  k6:
    image: grafana/k6
    container_name: k6
    depends_on:
      - demo-app
      - prometheus
    volumes:
      - ./k6:/scripts
    command: run --out experimental-prometheus-rw /scripts/test.js
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write