{
 "title": "TestOps Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests por segundo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{expected_response=\"true\"}[1m]))",
     "legendFormat": "OK (2xx)"
    },
    {
     "expr": "sum(rate(k6_http_reqs_total{expected_response=\"false\"}[1m]))",
     "legendFormat": "FAIL (4xx / 5xx)"
    }
   ]
  },
  {
   "title": "Total Casos",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 6, "h": 5 },
   "targets": [
    { "expr": "sum(k6_http_reqs_total)" }
   ]
  },
  {
   "title": "✅ Casos OK",
   "type": "stat",
   "gridPos": { "x": 6, "y": 8, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{expected_response=\"true\"})"
    }
   ]
  },
  {
   "title": "❌ Casos Failed",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 6, "h": 5 },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{expected_response=\"false\"})"
    }
   ]
  },
  {
   "title": "📘 HU en alcance",
   "type": "stat",
   "gridPos": { "x": 18, "y": 8, "w": 6, "h": 5 },
   "targets": [
    { "expr": "vector(18)" }
   ]
  },
  {
   "title": "🧪 HU probadas",
   "type": "stat",
   "gridPos": { "x": 0, "y": 13, "w": 6, "h": 5 },
   "targets": [
    { "expr": "vector(14)" }
   ]
  },
  {
   "title": "🐞 Defectos abiertos",
   "type": "stat",
   "gridPos": { "x": 6, "y": 13, "w": 6, "h": 5 },
   "targets": [
    { "expr": "vector(5)" }
   ]
  },
  {
   "title": "✅ Defectos cerrados",
   "type": "stat",
   "gridPos": { "x": 12, "y": 13, "w": 6, "h": 5 },
   "targets": [
    { "expr": "vector(21)" }
   ]
  }
 ]
}